### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by marurevi** [marurevi/Tasty-Recipes-API#21]
In this activity, our team prepared a Kanban board with a GitHub project.
- @marurevi is going to do "Student A" activities.
- @devMahmoud is going to do "Student B" activities.
- The link to the project is [link 🔗 ](https://github.com/marurevi/Breaking-News-API/projects/1)

**Comment by keroloussamy** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Kindly you have to assign each task to a team member, you can do that by clicking on the assignee option and selecting the tasks for that member.
![image](https://user-images.githubusercontent.com/35535130/168700257-af8d22a4-f9f1-48ec-b803-219461a0b202.png)


![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by keroloussamy** [comment]
Hi Team, 

Your project is complete!  
Congratulations! 🎉 



![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
